// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpfugmtetyqtdltomoft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZnVnbXRldHlxdGRsdG9tb2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMjg5OTcsImV4cCI6MjA5MDcwNDk5N30.vWn4pcodvV_rIchixjpSxBjeFpPgJpo3ReuGNKkFWMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});