// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uclqvvxmhiqjifilzrrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbHF2dnhtaGlxamlmaWx6cnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzNjk3ODcsImV4cCI6MjA5MDk0NTc4N30.2m1UVWPKOM4Ohz6OXBZ0b0GqOXDIC_p_UfIHzI0D2E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});